# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Requiem Labs'

# Test


# Build
jobs:
  - job: Build
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: '$env:BUILD_SOURCESDIRECTORY\build\build.ps1'