# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Requiem Labs Build'

# Setup versioning
jobs:
  - job: GitVersioning
    displayName: Git Versioning
    steps:
      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: '5.x'
      - task: gitversion/execute@0
        displayName: Determine Version
# Test
# Temporary
      - script: |
            echo Major: $(GitVersion.Major)
            echo Minor: $(GitVersion.Minor)
            echo Patch: $(GitVersion.Patch)
            echo PreReleaseTag: $(GitVersion.PreReleaseTag)
            echo PreReleaseTagWithDash: $(GitVersion.PreReleaseTagWithDash)
            echo PreReleaseLabel: $(GitVersion.PreReleaseLabel)
            echo PreReleaseNumber: $(GitVersion.PreReleaseNumber)
            echo WeightedPreReleaseNumber: $(GitVersion.WeightedPreReleaseNumber)
            echo BuildMetaData: $(GitVersion.BuildMetaData)
            echo BuildMetaDataPadded: $(GitVersion.BuildMetaDataPadded)
            echo FullBuildMetaData: $(GitVersion.FullBuildMetaData)
            echo MajorMinorPatch: $(GitVersion.MajorMinorPatch)
            echo SemVer: $(GitVersion.SemVer)
            echo LegacySemVer: $(GitVersion.LegacySemVer)
            echo LegacySemVerPadded: $(GitVersion.LegacySemVerPadded)
            echo AssemblySemVer: $(GitVersion.AssemblySemVer)
            echo AssemblySemFileVer: $(GitVersion.AssemblySemFileVer)
            echo FullSemVer: $(GitVersion.FullSemVer)
            echo InformationalVersion: $(GitVersion.InformationalVersion)
            echo BranchName: $(GitVersion.BranchName)
            echo EscapedBranchName: $(GitVersion.EscapedBranchName)
            echo Sha: $(GitVersion.Sha)
            echo ShortSha: $(GitVersion.ShortSha)
            echo NuGetVersionV2: $(GitVersion.NuGetVersionV2)
            echo NuGetVersion: $(GitVersion.NuGetVersion)
            echo NuGetPreReleaseTagV2: $(GitVersion.NuGetPreReleaseTagV2)
            echo NuGetPreReleaseTag: $(GitVersion.NuGetPreReleaseTag)
            echo VersionSourceSha: $(GitVersion.VersionSourceSha)
            echo CommitsSinceVersionSource: $(GitVersion.CommitsSinceVersionSource)
            echo CommitsSinceVersionSourcePadded: $(GitVersion.CommitsSinceVersionSourcePadded)
            echo UncommittedChanges: $(GitVersion.UncommittedChanges)
            echo CommitDate: $(GitVersion.CommitDate)

# Build

  - job: Build
    dependsOn: GitVersioning
    steps:
    - task: PowerShell@2
      inputs:
        filePath: '$(Build.SourcesDirectory)/build/build.ps1'